services:
  materias-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: materias-service
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SSL=${DATABASE_SSL}
      - PORT=3000
    restart: unless-stopped
    networks:
      - microservicios-topicos

networks:
  microservicios-topicos:
    external: true
